### ISSUE TITLE
Plugin ID does not match repository name.

### ISSUE THREAD

**Issue by stefan-jung** [dita-community/org.dita-community.split-page-sequences#4]
Hi @drmacro:

This is a little confusing 

plugin id =   org.dita-community.pdf.split-page-sequences
repository = org.dita-community.split-page-sequences

**Comment by drmacro** [comment]
Good catch--they should definitely match. I think it's easier to rename the plugin rather than move it to a new repo, if that works.

**Comment by drmacro** [comment]
Corrected the plug-in ID. No change required to users of the plug-in.
